# Generated by Django 5.2.1 on 2025-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
