# Generated by Django 5.2.1 on 2025-06-01 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_personalrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
