# Generated by Django 5.2.1 on 2025-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_personalrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
